# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Build lib
        uses: actions-rs/cargo@v1
        with:
          working-directory: lib/rs-qr
          command: build
          args: --release

      - name: Copy lib
        run: |
          cp lib/rs-qr/target/rs-qr.h ./lib
          cp lib/rs-qr/target/release/librs_qr.a ./lib
          cp lib/rs-qr/target/release/librs_qr.so ./lib

      - name: Build Go
        run: go build -v ./...

      - name: Test Go
        run: go test -v ./...
